Разметка главной страницы
htmlacademy-htmlcss/1390101-sedona-32 pull request #2
Opened 2021-09-27 19:07 UTC by Kris-js

---
:mortar_board: [Разметка главной страницы](https://up.htmlacademy.ru/htmlcss/32/user/1390101/tasks/3)

2021-09-27 23:22 UTC, wrgraff commented on index.html
> +    <a class="navigation-link" href="main.html">Главная</a>
Некоторые проверяющие на защите придираются к тому, что на странице есть ссылка на саму себя.
Хотя, критерий [HTML-03](https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-03) нам разрешает делать это на свое усмотрение:

> У ссылок должен быть атрибут href. Ссылки, которые ведут на самих себя, могут быть без атрибута.

2021-09-27 23:46 UTC, wrgraff commented on index.html
> +    <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Этот текст не очень хорошо описывает содержимое, поэтому больше подошел бы скрытый заголовок, а этот текст сделать просто текстом

2021-09-27 23:57 UTC, wrgraff commented on index.html
> +    <span class="visually-hidden">Подписаться</span>
Все хорошо с формой, но вдруг текст скрыт внутри кнопки.
Не внутри каждой кнопки текст должен быть скрыт, где он видим — там он должен быть видим и в разметке

2021-09-27 23:58 UTC, wrgraff commented on index.html
> +      <a class="button" href="#">
Почему класс `button`?

В лайве на Барбершопе так делали потому что в нем ссылки на соцсети выглядят так же, как и кнопки.

А у нас совсем не так, нам стили кнопки на этих ссылках будут совершенно лишними

https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/d93e55d88cdb77326bdb6f88cc5b8ce071eca082/index.html#L118
https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/d93e55d88cdb77326bdb6f88cc5b8ce071eca082/index.html#L123
https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/d93e55d88cdb77326bdb6f88cc5b8ce071eca082/index.html#L128

2021-09-27 23:58 UTC, wrgraff commented on index.html
> +<footer class="page-footer"
Закрывающую скобку потеряла
```suggestion
<footer class="page-footer">
```

2021-09-27 23:59 UTC, wrgraff commented on index.html
> +<a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a>
Я бы обратил внимание, что это можно использовать как часть пространства имен блока `page-footer`

2021-09-28 20:32 UTC, Kris-js commented on index.html
> +    <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Исправила.

2021-09-28 20:33 UTC, Kris-js commented on index.html
> +    <a class="navigation-link" href="main.html">Главная</a>
Исправила.

2021-09-28 20:35 UTC, Kris-js commented on index.html
> +      <a class="navigation-link" href="about.html">О Седоне</a>
Исправила.

2021-09-28 20:37 UTC, Kris-js commented on index.html
> +<img class="logo" src="" alt="логотип city of Sedona">
Исправила.

2021-09-28 20:38 UTC, Kris-js commented on index.html
> +      <span class="visually">
Исправила.

2021-09-28 20:41 UTC, Kris-js commented on index.html
> +        </span>
Исправила.

2021-09-28 20:41 UTC, Kris-js commented on index.html
> +<img class="welcome" src="" alt="Добро пожаловать в Седону">
Исправила.

2021-09-28 20:43 UTC, Kris-js commented on index.html
> +    <span>Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</span>
Исправила, поняла.

2021-09-28 20:48 UTC, Kris-js commented on index.html
> +        <h3 class="features-title">Жильё</h3>
Исправила, переделала на h4

2021-09-28 20:52 UTC, Kris-js commented on index.html
> +    <p class="advantages-description">— №1 — Седона — не аттракцион для туристов, там течёт
Исправила.

2021-09-28 20:54 UTC, Kris-js commented on index.html
> +        <img class="icon" src="" alt="Жильё">
убрала.

2021-09-28 20:56 UTC, Kris-js commented on index.html
> +        <li class="features-iteam">
Поправила.

2021-09-28 20:57 UTC, Kris-js commented on index.html
> +    <p class="advantages-description">— №2 — <br>Да, по нему можно пройти! Если вы осмелитесь, разумеется</p>
Исправила.

2021-09-28 20:58 UTC, Kris-js commented on index.html
> +<section class="Search">
Исправила.

2021-09-28 21:03 UTC, Kris-js commented on index.html
> +    <span class="visually-hidden">Подписаться</span>
Исправила.

2021-09-28 21:05 UTC, Kris-js commented on index.html
> +      <a class="button" href="#">
Убрала.

2021-09-28 21:06 UTC, Kris-js commented on index.html
> +<footer class="page-footer"
Исправила.

2021-09-28 21:17 UTC, Kris-js commented on index.html
> +<a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a>
Исправила, как поняла.

2021-09-29 23:57 UTC, wrgraff requested changes
Стало сильно лучше, но еще несколько моментов надо подправить

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +          <a class="navigation-link" href="#">Главная</a>
Нужно или оставить `index.html` или совсем убрать атрибут `href`. Ссылка без атрибута — это ссылка, которая сейчас никуда не ведет. А вот решетка — это заглушка на случай, если мы не знаем адрес. При чем, это для нас, для верстальщиков: на настоящем сайте конечно в итоге должны появиться все страницы

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +      <img class="logo" alt="логотип city of Sedona">
Я писал:

> Логотип обычно — ссылка на главную страницу (тоже можно без адреса, если мы на главной)

Надо было обернуть в ссылку без `href` =)
А ты убрала `src` из самой картинки

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +    <img class="welcome" src="" alt="welcome to the gargeous Sedona">
```suggestion
    <img class="welcome" src="" alt="welcome to the gorgeous Sedona">
```

Хотя текст там длиннее (и немного нецензурный, скажем прямо)

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +          <button class="button mailing-button" type="submit" value="Подписаться"></button>
Почему через `value`? Это же не инпут, а тег `<button>`.
Текст просто остается внутри кнопки:
```suggestion
          <button class="button mailing-button" type="submit">Подписаться</button>
```

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +          <a href="#">
Класс кнопки убрала, но какой-то класс им надо поставить все же:
https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/7b15c0d28b33f92c5fcf931a205440649e75dee1/index.html#L129
https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/7b15c0d28b33f92c5fcf931a205440649e75dee1/index.html#L134
https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/7b15c0d28b33f92c5fcf931a205440649e75dee1/index.html#L139

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +      <a class="page-footer-htmlacademy" href="https://htmlacademy.ru/">.html academy</a>
Лучше настолько к контенту не привязываться, а сделать класс более абстрактным (мало ли что там изменится). Например, так:
```suggestion
      <a class="page-footer-developer" href="https://htmlacademy.ru/">.html academy</a>
```

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +      <a class="page-footer-htmlacademy" href="https://htmlacademy.ru/">.html academy</a>
Хорошо бы еще и доступность "прокачать" =)
```suggestion
      <a class="page-footer-htmlacademy" href="https://htmlacademy.ru/">
        <span class="visually-hidden">Разработчик: </span>
        .html academy
      </a>
```

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +    <section class="footer-social">
Если это секшн для соцсетей, то он должен закрываться перед номером и ссылкой на академию, ведь они — не часть списка соцсетей

2021-09-29 23:57 UTC, wrgraff commented on index.html
> +          <p>Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
Только вот этот блок с общим заголовком и текстовым описанием идет внутри секции, но перед списком, а не внутри его первого пункта

2021-09-30 18:27 UTC, Kris-js commented on index.html
> +      <img class="logo" alt="логотип city of Sedona">
с атрибутом хреф разобралась)

2021-09-30 18:33 UTC, Kris-js commented on index.html
> +          <button class="button mailing-button" type="submit" value="Подписаться"></button>
А я то думаю, почему не отображается в браузере. Упустила этот момент

2021-09-30 18:35 UTC, Kris-js commented on index.html
> +    <img class="welcome" src="" alt="welcome to the gargeous Sedona">
Там дальше кавычки, я не хотела путать в разметке и писать большой текст к картинке. Или лучше добавить? Добавила)

2021-09-30 18:46 UTC, Kris-js commented on index.html
> +      <a class="page-footer-htmlacademy" href="https://htmlacademy.ru/">.html academy</a>
Ага, добавила)

2021-09-30 18:50 UTC, Kris-js commented on index.html
> +    <section class="footer-social">
Да я поняла. Видимо хотела весь футер секцией закрыть, хотя это не нужно.

2021-09-30 18:54 UTC, Kris-js commented on index.html
> +          <p>Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
Исправила.

2021-09-30 19:31 UTC, wrgraff approved these changes

2021-09-30 19:31 UTC, wrgraff commented on index.html
> +          <a class="navigation-link">
А здесь `href` куда уплыл )

2021-09-30 19:31 UTC, wrgraff commented on index.html
> +      <img class="logo" src="" alt="логотип city of Sedona">
Я имел ввиду, что лого — это ссылка на главную, то есть как в меню, только своя.
И надо сделать что-то такое:

```html
<a class="logo">
  <img class="logo-img" src="" alt="логотип city of Sedona">
</a>
```

2021-09-30 19:31 UTC, merged