разметка внутренней страницы
htmlacademy-htmlcss/1390101-sedona-32 pull request #3
Opened 2021-10-01 22:39 UTC by Kris-js

2021-10-02 14:00 UTC, wrgraff requested changes

2021-10-02 14:00 UTC, wrgraff commented on catalog.html
>        </form>
Надо, чтобы в форме были все поля, а не только кнопки. Иначе она отправит пустоту

2021-10-02 18:23 UTC, Kris-js commented on catalog.html
> +      <section class="hotel-card">
Исправила, поняла.

2021-10-02 18:29 UTC, Kris-js commented on catalog.html
> +            <a href="#" class="hotel-card-button button">В избранное</a>
добавила  blue и green.

2021-10-02 18:32 UTC, Kris-js commented on catalog.html
>          <ul class="catalog-filter-list">
добавила

2021-10-03 17:46 UTC, Kris-js commented on catalog.html
> +  <main>
Добавила page-main

2021-10-03 17:51 UTC, Kris-js commented on catalog.html
> +            <img class="hotel-rating-star" src="" alt="">
сделала через спан <span class="visually-hidden">4 звезды</span>

2021-10-03 18:14 UTC, Kris-js commented on catalog.html
>        </form>
Исправила

2021-10-03 18:14 UTC, Kris-js commented on catalog.html
>        <fieldset class="catalog-filter-group">
Вроде поняла)

2021-10-03 22:32 UTC, wrgraff approved these changes
Хорошо, можно еще кое-что улучшить, но сейчас уже годится!

2021-10-03 22:32 UTC, wrgraff commented on catalog.html
> +            <a href="#" class="hotel-card-button-blue ">В избранное</a>
Можно намного проще. У нас есть класс `.button`. Используй его для начала. А затем второй для цвета:
```suggestion
            <a href="#" class="button button-blue ">В избранное</a>
```

Такая же логика для кнопки "Подробнее". Только ей второй класс не нужен, у нее цвет по умолчанию

2021-10-03 22:32 UTC, wrgraff commented on catalog.html
> +            <span class="visually-hidden">4 звезды</span>
Не учла только что нам нужно еще и стилизовать что-то будет для оформления звезд:
```suggestion
            <p class="stars stars-4">
              <span class="visually-hidden">4 звезды</span>
            </p>
```

2021-10-03 22:32 UTC, wrgraff commented on catalog.html
> +      <form class="catalog-filter" action="" method="get">
форма появилась, но теперь нарушена вложенность

2021-10-03 22:32 UTC, merged

2021-10-04 06:34 UTC, Kris-js commented on catalog.html
> +            <a href="#" class="hotel-card-button-blue ">В избранное</a>
Добавила, но все равно не понимаю зачем нужен второй по сути дублирующий класс.

2021-10-04 06:38 UTC, Kris-js commented on catalog.html
> +            <span class="visually-hidden">4 звезды</span>
Думала над этим, добавила.