строит сетку каталога на гридах
htmlacademy-htmlcss/1390101-sedona-32 pull request #8
Opened 2021-11-02 21:12 UTC by Kris-js

2021-11-03 17:58 UTC, wrgraff requested changes

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +  grid-template-rows: 31px 23px 37px;
Считаем размеры строк и прибавляем гэпы.
`31 + 23 + 37 + (30 * 2) = 151`
151, а высота карточки — 120.

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +  grid-template-rows: 31px 23px 37px;
А еще если в тексте станет 2 строки или еще как-то контент изменится, то заданная высота не позволит ему получить доп пространство, и его контент наползет на контент другой линии

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +  grid-template-columns: 180px 319px 160px;
`180 + 319 + 160 + (30 * 2) = 719`
719, а ширина этих карточек 1056.

Кроме того, хорошо бы предусмотреть одну колонку со "свободной" шириной, чтобы финальный размер вообще контролировался контейнером.

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +  grid-row: 1;
Эти свойства не работают, это явно показывает и даже подсказывает браузер Firefox:
![изображение](https://user-images.githubusercontent.com/37917037/140164109-2f8b23d4-c03b-4940-99e5-30182925511f.png)

Почему не работает?
Очень просто. Этот тег не является элементом грид-контейнера. Им является ссылка `.hotel-card-link`, в которой он лежит (и для остальных элементов это тоже работает):
https://github.com/htmlacademy-htmlcss/1390101-sedona-32/blob/11f152c5020a31a7b5e76f06db172e9a0f8afacb/catalog.html#L172-L176

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +  display: grid;
А зачем задавать грид внутри картинки?
В ней даже элементов нет. Да и не может быть

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +.button button-secondary {
В данном селекторы ты выбираешь примерно вот такие элементы:

```html
<div class="button">
  <button-blue>
    ...
  </button-blue>

  <button-secondary>
    ...
  </button-secondary>
</div>
```

То есть, ты выбираешь теги, а не классы

2021-11-03 17:58 UTC, wrgraff commented on styles/styles.css
> +  grid-row: 2;
Элементов с классом `.hotel-card-desc` тоже 2. Ты их поставишь в одно место, получается

2021-11-06 16:02 UTC, wrgraff approved these changes
Принимаю, но постарайся поправить особенно те комментарии, что важны

2021-11-06 16:02 UTC, wrgraff commented on styles/styles.css
>  .button-sorting-active {
Обычно такой класс стоит вторым, и в нем приписывают только те стили, которые меняются для активного элемента

2021-11-06 16:02 UTC, wrgraff commented on styles/styles.css
>    display: flex;
Ссылки типов сортировки то так и стоят слева, а не справа.
Надо бы подправить. И я бы рекомендовал `.hotels-sorting` все-таки на гридах реализовать

2021-11-06 16:03 UTC, merged

2021-11-06 18:10 UTC, Kris-js commented on styles/styles.css
> +  grid-template-columns: 1fr 1fr 1fr;
исправила

2021-11-06 18:11 UTC, Kris-js commented on styles/styles.css
> +  justify-content: start;
Убрала

2021-11-06 18:13 UTC, Kris-js commented on styles/styles.css
> +  justify-content: flex-end;
Убрала

2021-11-06 18:14 UTC, Kris-js commented on styles/styles.css
>  .button-sorting-active {
Хотела, но не получилось так поставить. Стили снова пришлось дублировать